"""Fixed comment model

Revision ID: e63d4c07924e
Revises: 
Create Date: 2023-07-16 22:52:46.162168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63d4c07924e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tweet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tweet', ['tweet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tweet_id')

    # ### end Alembic commands ###
