version: '3.8'

services:

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: app
    command: ["docker/app.sh"]
    ports:
      - 6789:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    # На случай, если в Docker уже есть запущенные контейнеры с PostgresSQL на порту 5432
    command: -p 5432
    expose:
      - 5432
    ports:
      - 5432:5432
#    environment:
#      - POSTGRES_USER=${DB_USER:?err}
#      - POSTGRES_PASSWORD=${DB_PASS:?err}
#      - POSTGRES_DB=${DB_NAME:?err}
    env_file:
      - .env
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data